modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "leaf_treegen"
version = "0.1.0"
displayName = "LeafTreeGen"
description = "Procedural tree generation for Minecraft."

[[dependencies.leaf_treegen]]
modId = "neoforge"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.leaf_treegen]]
modId = "minecraft"
type = "required"
versionRange = "[26.1,)"
ordering = "NONE"
side = "BOTH"
